version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/react
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root

